const DEMO_HREF = 'https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ0opR77BM4HZuGTkYDqWCFBpzH8RY2GdNAcY29Y-gc9qRDw-uhYwU9OUjZdUD0FChiXP06wFKas'
const WA_HREF   = 'https://api.whatsapp.com/send?phone=573165267012&text=Hola%2C%20quiero%20hacer%20una%20pregunta%20acerca%20de%3A%20Escribo%20desde%20Ventas'

/* ════════════════════════════════════════════════════════════
   PRODUCT TRANSLATIONS  —  estructura idéntica al patrón
   useLang() del proyecto:  productTranslations[lang][key]
════════════════════════════════════════════════════════════ */
export const productTranslations = {

  /* ══════════════════════════════════════════════════
     ESPAÑOL
  ══════════════════════════════════════════════════ */
  es: {

    /* textos compartidos entre todas las páginas */
    shared: {
      demo:    'Solicitar demo',
      advisor: 'Hablar con un asesor',
      demoHref: DEMO_HREF,
      waHref:   WA_HREF,
    },

    /* ── 1. TRANSPORTE DE CARGA ──────────────────── */
    transCarga: {
      image: '/images/transport.jpg',
      bannerTitle:    'Controla toda tu operación de transporte sin errores ni reprocesos',
      bannerSubtitle: 'Desde la orden de cargue hasta la facturación y el pago de servicios. Gestiona tu operación de transporte de carga con un sistema que integra control operativo, contable y cumplimiento normativo en tiempo real.',
      bannerPoints: [
        'Control total de viajes, remesas y manifiestos',
        'Cumple con RNDC sin reprocesos',
        'Liquidaciones y anticipos automatizados',
        'Integración completa con contabilidad',
      ],
      featuresTitle: 'TODO TU PROCESO DE TRANSPORTE, EN UN SOLO SISTEMA',
      features: [
        { name: 'Tarifas y rentabilidad controlada',        desc: 'Define tarifas de cobro y pago, separando ingresos propios y de terceros con total claridad.' },
        { name: 'Control documental automático',            desc: 'Alertas de vencimiento de documentos de conductores y vehículos antes de que generen problemas operativos.' },
        { name: 'Información en tiempo real',               desc: 'Accede a informes de remesas, despachos, anticipos, facturación y resultados financieros en cualquier momento.' },
        { name: 'Operación completa de transporte',         desc: 'Gestiona desde la orden de cargue hasta la entrega final del servicio, con control total de cada movimiento.' },
        { name: 'Remesas, manifiestos y cumplidos',         desc: 'Administra todos los documentos operativos con trazabilidad completa y sin reprocesos.' },
        { name: 'Módulo jurídico integrado',                desc: 'Registra y conserva el historial de siniestros de vehículos para control y respaldo legal.' },
        { name: 'Integración con RNDC (tiempo real)',       desc: 'Conexión directa con el Ministerio de Transporte para envío automático de información, evitando errores y duplicidad de procesos.' },
        { name: 'Anticipos y liquidaciones sin errores',    desc: 'Parametriza presupuestos de anticipos y controla porcentajes máximos para evitar desviaciones financieras.' },
      ],
      whyTitle:    'No es un software genérico. Es un sistema diseñado para transporte real.',
      whySubtitle: 'SYSCOM Transporte de Carga no es un ERP adaptado. Es una solución creada específicamente para la operación del transporte en Colombia.',
      whyPoints: [
        'Integración total entre operación y contabilidad',
        'Cumplimiento con normativas del Ministerio de Transporte',
        'Conexión en línea con RNDC (sin reprocesos)',
        'Adaptado a la lógica real de empresas transportadoras',
        'Parametrización avanzada según tu operación',
      ],
      whyClosing:     'Mientras otros sistemas te obligan a adaptarte, SYSCOM se adapta a tu empresa.',
      benefitsTitle:  'LO QUE CAMBIA CUANDO TIENES CONTROL REAL',
      benefits: [
        { title: 'Menos errores, más eficiencia',   desc: 'Elimina reprocesos y errores manuales en liquidaciones, documentos y operación.' },
        { title: 'Decisiones con datos reales',     desc: 'Accede a información confiable y actualizada para tomar decisiones operativas y financieras.' },
        { title: 'Operación conectada',             desc: 'Todo fluye en un solo sistema: viajes, documentos, contabilidad y control financiero.' },
        { title: 'Mayor rentabilidad',              desc: 'Controla anticipos, costos y tarifas para mejorar la rentabilidad de cada viaje.' },
        { title: 'Cumplimiento sin estrés',         desc: 'Cumple con RNDC y normativa sin depender de procesos manuales o externos.' },
      ],
      closingTitle: 'SI NO TIENES CONTROL, ESTÁS PERDIENDO DINERO',
      closingDesc:  'Deja de depender de procesos manuales, errores operativos y sistemas desconectados. Empieza a gestionar tu empresa de transporte con una solución diseñada para tu realidad.',
    },

    /* ── 2. TRANSPORTE ESPECIAL ──────────────────── */
    transporteEspecial: {
      image: '/images/transport.jpg',
      bannerTitle:    'Gestiona tu operación de transporte especial con precisión y control total',
      bannerSubtitle: 'Administra rutas, contratos, pasajeros y flota desde un solo sistema. SYSCOM Transporte Especial integra la operación con la facturación y la contabilidad, eliminando reprocesos y mejorando el control de cada servicio.',
      bannerPoints: [
        'Control de rutas y manifiestos de pasajeros',
        'Facturación por contrato, ruta o servicio',
        'Gestión de conductores y flota asignada',
        'Integración automática con contabilidad',
      ],
      featuresTitle: 'TODO TU PROCESO DE TRANSPORTE ESPECIAL, EN UN SOLO SISTEMA',
      features: [
        { name: 'Gestión de contratos y rutas',         desc: 'Define contratos por empresa o entidad, asigna rutas y controla el cumplimiento de cada servicio.' },
        { name: 'Control de manifiestos de pasajeros',  desc: 'Registra la lista de pasajeros por ruta o servicio con trazabilidad completa y documentación en orden.' },
        { name: 'Programación y despacho de flota',     desc: 'Planifica horarios, asigna vehículos y conductores, y controla el despacho en tiempo real.' },
        { name: 'Facturación por servicio o contrato',  desc: 'Emite facturas electrónicas directamente desde los servicios prestados, agilizando el cobro.' },
        { name: 'Control documental de conductores',    desc: 'Alertas de vencimiento de licencias, seguros y documentos de vehículos antes de que sean un problema.' },
        { name: 'Anticipos y liquidaciones',            desc: 'Parametriza anticipos a conductores y controla liquidaciones con exactitud sin cálculos manuales.' },
        { name: 'Módulo jurídico y siniestros',         desc: 'Historial de siniestros y novedades por vehículo para respaldo legal y control de la flota.' },
        { name: 'Información financiera en tiempo real',desc: 'Reportes de ingresos, costos por ruta y rentabilidad por contrato disponibles en cualquier momento.' },
      ],
      whyTitle:    'No es un sistema genérico. Es software pensado para transporte especial real.',
      whySubtitle: 'SYSCOM Transporte Especial fue diseñado para empresas que operan contratos de transporte de personal, escolar, turístico o ejecutivo en Colombia.',
      whyPoints: [
        'Lógica operativa adaptada a transporte especial y de personal',
        'Facturación integrada con la operación sin doble digitación',
        'Control de flota y conductores desde un solo módulo',
        'Cumplimiento con normativa del Ministerio de Transporte',
        'Parametrización flexible según tu tipo de operación',
      ],
      whyClosing:    'Tu operación tiene reglas propias. SYSCOM se adapta a ellas, no al revés.',
      benefitsTitle: 'LO QUE CAMBIA CUANDO TIENES CONTROL REAL',
      benefits: [
        { title: 'Menos errores operativos',      desc: 'Elimina reprocesos en documentación, manifiestos y liquidaciones de conductores.' },
        { title: 'Facturación más ágil',          desc: 'Genera facturas electrónicas directamente desde los servicios prestados sin pasos adicionales.' },
        { title: 'Flota bajo control',            desc: 'Seguimiento de vehículos, conductores y vencimientos en un solo lugar.' },
        { title: 'Mayor rentabilidad por contrato', desc: 'Analiza costos e ingresos por contrato o ruta para tomar decisiones con información real.' },
        { title: 'Cumplimiento normativo garantizado', desc: 'Opera con las exigencias del Ministerio de Transporte sin depender de procesos externos.' },
      ],
      closingTitle: 'SI NO TIENES CONTROL, ESTÁS PERDIENDO RENTABILIDAD',
      closingDesc:  'Deja de administrar tus contratos y rutas con hojas de cálculo. Gestiona tu empresa de transporte especial con un sistema diseñado para tu operación.',
    },

    /* ── 3. BUS URBANO ───────────────────────────── */
    busUrbano: {
      image: '/images/transport.jpg',
      bannerTitle:    'Controla tus rutas urbanas, flota y operación desde un solo sistema',
      bannerSubtitle: 'Gestiona la programación de rutas, el control de despachos, los ingresos por rodada y la flota de buses con un sistema integrado que conecta la operación con la contabilidad.',
      bannerPoints: [
        'Control de rutas, turnos y despachos',
        'Liquidación de conductores y planillaje',
        'Gestión de flota y mantenimiento preventivo',
        'Integración con contabilidad y facturación',
      ],
      featuresTitle: 'TODO TU PROCESO DE TRANSPORTE URBANO, EN UN SOLO SISTEMA',
      features: [
        { name: 'Gestión de rutas y turnos',          desc: 'Define rutas, turnos y horarios de despacho con control total de la programación diaria.' },
        { name: 'Control de despachos en tiempo real',desc: 'Registra salidas y llegadas, controla frecuencias y detecta desviaciones operativas de inmediato.' },
        { name: 'Liquidación a conductores',          desc: 'Calcula automáticamente ingresos, descuentos y pago a conductores según rodada y planilla.' },
        { name: 'Control de planillaje',              desc: 'Administra los ingresos por planilla de cada bus con total precisión y sin cálculos manuales.' },
        { name: 'Gestión de flota y propietarios',    desc: 'Controla la información de cada vehículo, propietario y afiliado dentro del sistema.' },
        { name: 'Mantenimiento preventivo y correctivo', desc: 'Programa mantenimientos, registra trabajos realizados y controla costos de taller por vehículo.' },
        { name: 'Control documental automático',      desc: 'Alertas de vencimiento de SOAT, tecnicomecánica y documentos de conductores.' },
        { name: 'Reportes financieros por ruta',      desc: 'Analiza ingresos, costos y rentabilidad por ruta, vehículo o período con información en tiempo real.' },
      ],
      whyTitle:    'Diseñado para la operación real de empresas de transporte urbano.',
      whySubtitle: 'SYSCOM Bus Urbano no es un software genérico adaptado. Es una solución construida para la lógica operativa del transporte urbano y de pasajeros en Colombia.',
      whyPoints: [
        'Planillaje y liquidación integrados con contabilidad',
        'Control de despachos y frecuencias en tiempo real',
        'Módulo de afiliados y propietarios de vehículos',
        'Cumplimiento con normativa del Ministerio de Transporte',
        'Parametrización según el modelo operativo de tu empresa',
      ],
      whyClosing:    'Cada empresa de bus tiene su lógica. SYSCOM se adapta a la tuya.',
      benefitsTitle: 'LO QUE CAMBIA CUANDO TIENES CONTROL REAL',
      benefits: [
        { title: 'Liquidaciones sin errores',        desc: 'Automatiza el cálculo de planillas y pago a conductores, eliminando diferencias manuales.' },
        { title: 'Operación más organizada',         desc: 'Despachos, turnos y rutas controlados desde un solo sistema sin papeles ni hojas de cálculo.' },
        { title: 'Información financiera clara',     desc: 'Conoce la rentabilidad de cada ruta y vehículo con reportes actualizados en tiempo real.' },
        { title: 'Flota documentada y al día',       desc: 'Documentos de vehículos y conductores siempre monitoreados para evitar problemas legales.' },
        { title: 'Decisiones con datos reales',      desc: 'Deja de operar con intuición y empieza a decidir con información confiable del sistema.' },
      ],
      closingTitle: 'TU FLOTA URBANA MERECE UN SISTEMA A SU ALTURA',
      closingDesc:  'Moderniza la gestión de tu empresa de transporte urbano con un sistema integrado que conecta la operación, la flota y las finanzas en tiempo real.',
    },

    /* ── 4. MANTENIMIENTO VEHICULAR ──────────────── */
    mantvehicular: {
      image: '/images/transport.jpg',
      bannerTitle:    'Controla el mantenimiento de tu flota sin pérdidas ni imprevistos',
      bannerSubtitle: 'Programa mantenimientos preventivos, gestiona órdenes de trabajo, controla el inventario de repuestos y analiza los costos de taller desde un solo sistema integrado.',
      bannerPoints: [
        'Programación de mantenimientos preventivos y correctivos',
        'Órdenes de trabajo con trazabilidad completa',
        'Control de repuestos e inventario de taller',
        'Costos de mantenimiento por vehículo en tiempo real',
      ],
      featuresTitle: 'TODO EL CONTROL DE TU TALLER Y FLOTA, EN UN SOLO SISTEMA',
      features: [
        { name: 'Programación de mantenimientos',   desc: 'Define planes de mantenimiento por kilometraje o tiempo y recibe alertas automáticas de vencimiento.' },
        { name: 'Órdenes de trabajo',               desc: 'Crea, asigna y hace seguimiento a órdenes de trabajo con estado, técnico y costos asociados.' },
        { name: 'Control de repuestos e inventario',desc: 'Administra el inventario de partes y repuestos del taller con control de entradas, salidas y stock mínimo.' },
        { name: 'Historial por vehículo',           desc: 'Consulta el historial completo de mantenimientos, reparaciones y costos de cada vehículo.' },
        { name: 'Control de costos de taller',      desc: 'Registra mano de obra, repuestos y servicios externos para conocer el costo real por intervención.' },
        { name: 'Alertas documentales de flota',    desc: 'Control de vencimiento de SOAT, tecnicomecánica y documentos reglamentarios por vehículo.' },
        { name: 'Gestión de proveedores de taller', desc: 'Controla compras a proveedores de repuestos y servicios de mantenimiento externo.' },
        { name: 'Reportes de mantenimiento',        desc: 'Informes de costos, intervenciones y disponibilidad de flota para tomar decisiones operativas.' },
      ],
      whyTitle:    'Un sistema pensado para la gestión real de flotas en Colombia.',
      whySubtitle: 'SYSCOM Mantenimiento Vehicular no es solo un módulo de control. Es una solución que conecta el taller con la operación y las finanzas de tu empresa.',
      whyPoints: [
        'Historial técnico completo por vehículo',
        'Integración con inventarios y compras',
        'Control de costos real por intervención',
        'Alertas automáticas de mantenimientos programados',
        'Adaptado a flotas de transporte de carga, especial y urbano',
      ],
      whyClosing:    'Un vehículo sin mantenimiento controlado es una pérdida anunciada. SYSCOM lo previene.',
      benefitsTitle: 'LO QUE CAMBIA CUANDO TIENES CONTROL REAL DE TU FLOTA',
      benefits: [
        { title: 'Menos vehículos varados',        desc: 'Los mantenimientos programados reducen fallas imprevistas y tiempo de inactividad de la flota.' },
        { title: 'Costos bajo control',            desc: 'Conoce exactamente cuánto cuesta mantener cada vehículo y toma decisiones con información real.' },
        { title: 'Inventario de repuestos preciso',desc: 'Evita desabastecimiento o sobreinventario con un control automatizado del stock del taller.' },
        { title: 'Flota documentada',              desc: 'Todos los documentos, revisiones y trabajos realizados quedan registrados y disponibles.' },
        { title: 'Mayor vida útil de la flota',    desc: 'El mantenimiento preventivo sistemático extiende la vida útil de los vehículos y reduce costos.' },
      ],
      closingTitle: 'TU FLOTA ES TU NEGOCIO. PROTÉGELA CON CONTROL REAL.',
      closingDesc:  'Deja de depender de hojas de cálculo y recordatorios manuales. Gestiona el mantenimiento de tu flota con un sistema que trabaja por ti.',
    },

    /* ── 5. PARQUEADERO ──────────────────────────── */
    parqueadero: {
      image: '/images/138148.jpg',
      bannerTitle:    'Controla tu parqueadero con precisión, velocidad y sin pérdidas',
      bannerSubtitle: 'Administra entradas, salidas, tarifas y facturación de tu parqueadero desde un sistema integrado que te da visibilidad total del negocio en tiempo real.',
      bannerPoints: [
        'Control de entrada y salida de vehículos',
        'Tarifas flexibles por tiempo, tipo de vehículo o mensualidad',
        'Facturación electrónica integrada',
        'Reportes de ingresos y ocupación en tiempo real',
      ],
      featuresTitle: 'TODO EL CONTROL DE TU PARQUEADERO, EN UN SOLO SISTEMA',
      features: [
        { name: 'Control de entrada y salida',        desc: 'Registra la entrada y salida de cada vehículo con hora exacta, placa y tiempo de permanencia.' },
        { name: 'Tarifas por tiempo o tipo',          desc: 'Define tarifas horarias, diarias o por tipo de vehículo con cálculo automático al momento del cobro.' },
        { name: 'Mensualidades y abonos',             desc: 'Gestiona usuarios con mensualidad o abono, controla vigencia y genera cobros automáticos.' },
        { name: 'Facturación electrónica DIAN',       desc: 'Emite facturas electrónicas en el momento del cobro, cumpliendo con la normativa vigente.' },
        { name: 'Control de caja y formas de pago',   desc: 'Registra cobros en efectivo, tarjeta o transferencia con cuadre de caja por turno.' },
        { name: 'Ocupación en tiempo real',           desc: 'Consulta cuántos vehículos hay en el parqueadero, disponibilidad por zona y rotación diaria.' },
        { name: 'Reportes de ingresos',               desc: 'Informes de ingresos por turno, día, semana o mes para análisis financiero del negocio.' },
        { name: 'Control multiusuario por turno',     desc: 'Administra accesos por operador y controla cuadres de caja por cada turno de trabajo.' },
      ],
      whyTitle:    'Más que un software de cobros. Un sistema de control total para tu parqueadero.',
      whySubtitle: 'SYSCOM Parqueadero fue diseñado para administradores y operadores que necesitan control real sobre su operación, ingresos y cumplimiento normativo.',
      whyPoints: [
        'Facturación electrónica integrada desde el cobro',
        'Control de caja por operador y turno',
        'Reportes financieros para la toma de decisiones',
        'Parametrización de tarifas según tu modelo de negocio',
        'Integración con contabilidad sin doble digitación',
      ],
      whyClosing:    'Cada vehículo que entra o sale es una transacción. SYSCOM no deja ninguna sin registrar.',
      benefitsTitle: 'LO QUE CAMBIA CUANDO TIENES CONTROL REAL',
      benefits: [
        { title: 'Sin fugas de ingresos',      desc: 'Cada servicio queda registrado y cobrado correctamente, eliminando pérdidas por errores manuales.' },
        { title: 'Cobros más rápidos',         desc: 'El sistema calcula automáticamente el valor a cobrar, agilizando la atención en cada salida.' },
        { title: 'Facturación al día',         desc: 'Cumple con la DIAN emitiendo facturas electrónicas en tiempo real desde el punto de cobro.' },
        { title: 'Información clara del negocio', desc: 'Conoce tus ingresos, ocupación y rotación con reportes actualizados en cualquier momento.' },
        { title: 'Operación organizada por turno', desc: 'Cada operador responde por su turno con cuadres de caja precisos y trazabilidad completa.' },
      ],
      closingTitle: 'TU PARQUEADERO BIEN ADMINISTRADO ES MÁS RENTABLE',
      closingDesc:  'Elimina los errores de cobro, las pérdidas por procesos manuales y la falta de control. Empieza a gestionar tu parqueadero con un sistema que trabaja contigo.',
    },

    /* ── 6. ESTACIONES DE SERVICIO ───────────────── */
    estaciones: {
      image: '/images/138148.jpg',
      bannerTitle:    'Control total de tu estación de servicio, desde el tanque hasta la factura',
      bannerSubtitle: 'Administra inventarios, despachos de combustible, ventas y reportes operativos con un sistema que integra todos los procesos en tiempo real y bajo normativa vigente.',
      bannerPoints: [
        'Control de inventario por tanques y productos',
        'Despacho de combustible integrado con caja',
        'Facturación electrónica DIAN en tiempo real',
        'Reportes operativos y financieros completos',
      ],
      featuresTitle: 'TODO EL CONTROL DE TU ESTACIÓN, EN UN SOLO SISTEMA',
      features: [
        { name: 'Control de tanques e inventario',  desc: 'Monitorea niveles de combustible por tanque, registra entradas y controla el inventario de productos.' },
        { name: 'Despacho de combustible',          desc: 'Registra despachos por surtidor, producto y valor con trazabilidad completa de cada transacción.' },
        { name: 'Ventas en tienda y lubricantes',   desc: 'Controla las ventas de tienda, aceites y servicios complementarios integradas con la facturación.' },
        { name: 'Facturación electrónica DIAN',     desc: 'Emite facturas electrónicas desde el punto de venta cumpliendo con los requerimientos vigentes.' },
        { name: 'Control de caja y formas de pago', desc: 'Registra pagos en efectivo, tarjeta, bonos o crédito con cuadre automático por turno.' },
        { name: 'Compras y abastecimiento',         desc: 'Gestiona las órdenes de compra de combustible y productos para mantener el abastecimiento controlado.' },
        { name: 'Reportes operativos completos',    desc: 'Informes de ventas por turno, producto, surtidor y período para análisis total del negocio.' },
        { name: 'Integración con contabilidad',     desc: 'Las ventas, compras e inventarios se integran automáticamente con la contabilidad sin reprocesos.' },
      ],
      whyTitle:    'No es un software de cobros. Es control total para tu estación de servicio.',
      whySubtitle: 'SYSCOM Estaciones de Servicio fue desarrollado para operadores que necesitan manejar múltiples productos, turnos y reportes con precisión y cumplimiento normativo.',
      whyPoints: [
        'Inventario por tanque actualizado en cada despacho',
        'Facturación electrónica integrada con la operación',
        'Control de turnos y caja sin diferencias',
        'Reportes para decisiones operativas y financieras',
        'Adaptado a la operación real de estaciones en Colombia',
      ],
      whyClosing:    'Cada litro despachado es una transacción. SYSCOM las registra todas con precisión.',
      benefitsTitle: 'LO QUE CAMBIA CUANDO TIENES CONTROL REAL',
      benefits: [
        { title: 'Control de inventario sin pérdidas', desc: 'Conoce exactamente cuánto combustible y producto tienes en tiempo real sin diferencias.' },
        { title: 'Cumplimiento normativo garantizado', desc: 'Factura electrónicamente y opera bajo la normativa vigente sin procesos manuales.' },
        { title: 'Caja cuadrada por turno',            desc: 'Cada turno cierra con cuadre exacto, evitando diferencias y pérdidas no identificadas.' },
        { title: 'Información para decidir mejor',    desc: 'Reportes de ventas, márgenes y rotación disponibles en cualquier momento del día.' },
        { title: 'Operación conectada',               desc: 'Despachos, ventas, compras y contabilidad integrados en un solo sistema sin doble digitación.' },
      ],
      closingTitle: 'TU ESTACIÓN SIN CONTROL ES UNA ESTACIÓN SIN RENTABILIDAD',
      closingDesc:  'Deja de operar con diferencias en inventario y cierres manuales. Integra tu operación completa con un sistema diseñado para estaciones de servicio.',
    },

    /* ── 7. PLANTAS INDUSTRIALES ─────────────────── */
    plantas: {
      image: '/images/138148.jpg',
      bannerTitle:    'Gestiona tu planta industrial con control total de procesos, costos y personal',
      bannerSubtitle: 'Integra la gestión de inventarios, activos, nómina y contabilidad en un solo sistema que optimiza los procesos productivos y mejora la eficiencia operativa de tu planta.',
      bannerPoints: [
        'Control de inventarios y materiales de producción',
        'Gestión de activos fijos y depreciación',
        'Nómina y administración de personal integradas',
        'Costos operativos y contabilidad en tiempo real',
      ],
      featuresTitle: 'TODO EL CONTROL DE TU PLANTA, EN UN SOLO SISTEMA',
      features: [
        { name: 'Gestión de inventarios y materiales', desc: 'Controla entradas, salidas y stock de materias primas, insumos y productos terminados.' },
        { name: 'Control de activos fijos',            desc: 'Registra maquinaria, equipos e instalaciones con cálculo automático de depreciación.' },
        { name: 'Costos de producción y operativos',   desc: 'Analiza los costos reales de cada proceso productivo para mejorar la eficiencia y rentabilidad.' },
        { name: 'Nómina y gestión de personal',        desc: 'Administra contratos, nómina electrónica y novedades de personal integrado con contabilidad.' },
        { name: 'Órdenes de compra y proveedores',     desc: 'Gestiona la compra de insumos y materiales con control de proveedores y condiciones de pago.' },
        { name: 'Control de facturación y ventas',     desc: 'Registra ventas de productos y emite facturas electrónicas desde el mismo sistema.' },
        { name: 'Informes contables y financieros',    desc: 'Estados financieros, balances y reportes para la DIAN generados automáticamente.' },
        { name: 'Integración total de módulos',        desc: 'Inventario, activos, nómina y contabilidad trabajan juntos sin digitación doble ni reprocesos.' },
      ],
      whyTitle:    'Un sistema que entiende la operación de una planta industrial real.',
      whySubtitle: 'SYSCOM Plantas Industriales integra todos los procesos administrativos y operativos de tu planta en una sola plataforma, sin módulos desconectados ni información duplicada.',
      whyPoints: [
        'Integración de inventario, activos, nómina y contabilidad',
        'Costos de producción calculados automáticamente',
        'Cumplimiento con normativa DIAN y laboral colombiana',
        'Gestión de proveedores y compras en el mismo sistema',
        'Parametrización según el modelo productivo de tu empresa',
      ],
      whyClosing:    'Una planta bien controlada es una planta más rentable. SYSCOM te da ese control.',
      benefitsTitle: 'LO QUE CAMBIA CUANDO TIENES CONTROL REAL',
      benefits: [
        { title: 'Costos reales de producción',    desc: 'Conoce exactamente cuánto cuesta producir con información actualizada de inventario y recursos.' },
        { title: 'Inventario siempre preciso',     desc: 'Controla materias primas, insumos y productos terminados sin diferencias ni errores manuales.' },
        { title: 'Nómina integrada sin reprocesos',desc: 'Procesa la nómina y regístrala contablemente sin salir del sistema.' },
        { title: 'Activos bajo control',           desc: 'Conoce el valor actualizado de tu maquinaria y equipos con depreciación automática.' },
        { title: 'Decisiones basadas en datos',    desc: 'Información financiera y operativa en tiempo real para gestionar tu planta con confianza.' },
      ],
      closingTitle: 'OPERA TU PLANTA CON EL CONTROL QUE TU NEGOCIO MERECE',
      closingDesc:  'Integra los procesos de tu planta industrial en un solo sistema y deja de depender de información dispersa, sistemas desconectados y procesos manuales.',
    },

    /* ── 8. SYSTOTAL COMERCIAL ───────────────────── */
    sysTotalComercial: {
      image: '/images/about.jpg',
      bannerTitle:    'Controla toda la gestión comercial de tu empresa sin errores ni reprocesos',
      bannerSubtitle: 'Desde la cotización hasta el cobro, SYSCOM Total Comercial integra ventas, compras, inventario y facturación en un solo sistema que le da control real a tu operación comercial.',
      bannerPoints: [
        'Ciclo comercial completo: cotización, pedido, factura',
        'Control de inventario y stock en tiempo real',
        'Gestión de cartera, cobros y cuentas por pagar',
        'Integración con contabilidad sin doble digitación',
      ],
      featuresTitle: 'TODO TU PROCESO COMERCIAL, EN UN SOLO SISTEMA',
      features: [
        { name: 'Cotizaciones y pedidos',             desc: 'Genera cotizaciones profesionales, conviértelas en pedidos y controla su estado hasta la facturación.' },
        { name: 'Facturación electrónica DIAN',       desc: 'Emite facturas, notas crédito y débito electrónicas cumpliendo con todos los requisitos vigentes.' },
        { name: 'Control de inventario',              desc: 'Administra el stock de productos con control de entradas, salidas, precios de costo y venta.' },
        { name: 'Gestión de compras',                 desc: 'Crea órdenes de compra, controla proveedores y registra las entradas de mercancía al inventario.' },
        { name: 'Cartera y cuentas por cobrar',       desc: 'Controla los saldos de tus clientes, vencimientos y gestiona el cobro de forma eficiente.' },
        { name: 'Cuentas por pagar a proveedores',    desc: 'Administra las obligaciones con proveedores, fechas de pago y flujo de caja.' },
        { name: 'Listas de precios y descuentos',     desc: 'Define múltiples listas de precios, descuentos por cliente o cantidad, y condiciones comerciales.' },
        { name: 'Reportes de ventas y rentabilidad',  desc: 'Informes de ventas por vendedor, producto, cliente o período para análisis completo del negocio.' },
      ],
      whyTitle:    'No es un ERP complejo. Es el sistema comercial que tu empresa necesita.',
      whySubtitle: 'SYSCOM Total Comercial está diseñado para empresas colombianas que necesitan controlar su operación comercial de forma integral, sin complicaciones y cumpliendo con la normativa.',
      whyPoints: [
        'Ciclo comercial completo en un solo sistema',
        'Facturación electrónica certificada por la DIAN',
        'Control de inventario integrado con ventas y compras',
        'Gestión de cartera y proveedores automatizada',
        'Reportes para toma de decisiones comerciales y financieras',
      ],
      whyClosing:    'Mientras otros sistemas te complican, SYSCOM te simplifica la operación sin perder control.',
      benefitsTitle: 'LO QUE CAMBIA CUANDO TIENES CONTROL REAL',
      benefits: [
        { title: 'Ventas sin errores',            desc: 'Desde la cotización hasta la factura electrónica, todo el ciclo fluye sin reprocesos ni errores.' },
        { title: 'Inventario siempre actualizado',desc: 'Cada venta o compra actualiza el stock automáticamente, eliminando diferencias de inventario.' },
        { title: 'Cartera bajo control',          desc: 'Conoce en todo momento qué te deben tus clientes y qué debes a tus proveedores.' },
        { title: 'Cumplimiento DIAN garantizado', desc: 'Factura electrónicamente y genera los reportes tributarios sin esfuerzo adicional.' },
        { title: 'Información para crecer',       desc: 'Reportes de ventas, márgenes y rentabilidad para tomar decisiones con datos reales.' },
      ],
      closingTitle: 'TU EMPRESA COMERCIAL NECESITA MÁS QUE UNA HOJA DE CÁLCULO',
      closingDesc:  'Deja de gestionar tu negocio con sistemas desconectados. Integra toda tu operación comercial y empieza a crecer con control real.',
    },

    /* ── 9. NÓMINA RH ────────────────────────────── */
    nominarh: {
      image: '/images/about.jpg',
      bannerTitle:    'Liquida la nómina de tu empresa sin errores y cumple con la DIAN',
      bannerSubtitle: 'Gestiona contratos, calcula liquidaciones, genera nómina electrónica y administra novedades de personal desde un sistema integrado que elimina errores y reprocesos.',
      bannerPoints: [
        'Liquidación de nómina automática y sin errores',
        'Nómina electrónica certificada por la DIAN',
        'Control de novedades: incapacidades, vacaciones, horas extra',
        'Seguridad social y parafiscales liquidados automáticamente',
      ],
      featuresTitle: 'TODO EL CONTROL DE TU NÓMINA Y PERSONAL, EN UN SOLO SISTEMA',
      features: [
        { name: 'Liquidación automática de nómina',  desc: 'Calcula salarios, deducciones, prestaciones y neto a pagar con exactitud y sin fórmulas manuales.' },
        { name: 'Nómina electrónica DIAN',           desc: 'Genera y transmite el documento soporte de pago de nómina electrónica cumpliendo con la normativa vigente.' },
        { name: 'Control de novedades',              desc: 'Registra incapacidades, vacaciones, horas extra, permisos y ausencias para su liquidación correcta.' },
        { name: 'Seguridad social y aportes',        desc: 'Calcula automáticamente los aportes a EPS, pensión, ARL y parafiscales por cada empleado.' },
        { name: 'Contratos y vinculaciones',         desc: 'Administra contratos, tipos de vinculación, salarios y beneficios del personal de forma organizada.' },
        { name: 'Liquidación de prestaciones sociales', desc: 'Calcula cesantías, intereses, prima de servicios y vacaciones con exactitud en cualquier momento.' },
        { name: 'Comprobantes de nómina',            desc: 'Genera desprendibles de pago individuales para cada empleado con detalle completo de la liquidación.' },
        { name: 'Integración con contabilidad',      desc: 'La nómina se registra contablemente de forma automática, eliminando la doble digitación.' },
      ],
      whyTitle:    'Nómina sin errores, sin multas y sin reprocesos. Eso es SYSCOM Nómina.',
      whySubtitle: 'SYSCOM Nómina RH fue diseñado para empresas colombianas que necesitan liquidar su nómina con exactitud, cumplir con la DIAN y gestionar su personal de manera organizada.',
      whyPoints: [
        'Cálculo automático de nómina según normativa colombiana vigente',
        'Nómina electrónica integrada sin procesos adicionales',
        'Seguridad social y parafiscales calculados sin errores',
        'Historial de empleados y novedades centralizado',
        'Integración directa con contabilidad y pagos',
      ],
      whyClosing:    'Liquidar nómina manualmente es un riesgo. SYSCOM lo convierte en un proceso confiable.',
      benefitsTitle: 'LO QUE CAMBIA CUANDO TIENES CONTROL REAL DE TU NÓMINA',
      benefits: [
        { title: 'Liquidaciones exactas',         desc: 'Elimina errores en cálculos de salarios, prestaciones y deducciones.' },
        { title: 'Cumplimiento DIAN garantizado', desc: 'Genera la nómina electrónica sin esfuerzo adicional y cumple con la normativa vigente.' },
        { title: 'Tiempo ahorrado',               desc: 'Lo que antes tomaba días en hojas de cálculo ahora se liquida en minutos.' },
        { title: 'Personal organizado',           desc: 'Historial de contratos, novedades y pagos disponible en todo momento para consultas y auditorías.' },
        { title: 'Sin multas ni sanciones',       desc: 'Cumple oportunamente con seguridad social, parafiscales y reportes tributarios.' },
      ],
      closingTitle: 'UN ERROR EN NÓMINA PUEDE COSTARTE MÁS QUE EL SISTEMA',
      closingDesc:  'Protege a tu empresa de errores, multas y reprocesos. Gestiona la nómina de tu equipo con un sistema diseñado para la realidad empresarial colombiana.',
    },

    /* ── 10. CONTABILIDAD ────────────────────────── */
    contabilidad: {
      image: '/images/about.jpg',
      bannerTitle:    'Lleva la contabilidad de tu empresa con precisión, orden y cumplimiento normativo',
      bannerSubtitle: 'Registra movimientos contables, genera estados financieros, cumple con la DIAN y toma decisiones con información confiable y actualizada desde un sistema integrado.',
      bannerPoints: [
        'Plan de cuentas y registros contables automatizados',
        'Informes financieros: balance, P&G, flujo de caja',
        'Reportes tributarios: exógena, retención, IVA',
        'Integración con nómina, facturación e inventarios',
      ],
      featuresTitle: 'TODO EL CONTROL CONTABLE DE TU EMPRESA, EN UN SOLO SISTEMA',
      features: [
        { name: 'Plan de cuentas parametrizable',   desc: 'Configura el plan de cuentas según la normativa colombiana y las necesidades específicas de tu empresa.' },
        { name: 'Registros y asientos contables',   desc: 'Captura comprobantes de ingreso, egreso, diario y ajustes con total trazabilidad y control de aprobación.' },
        { name: 'Estados financieros automáticos',  desc: 'Genera balance general, estado de resultados y flujo de caja actualizados en tiempo real.' },
        { name: 'Reportes para la DIAN',            desc: 'Prepara información exógena, reportes de retención en la fuente, IVA y medios magnéticos sin reprocesos.' },
        { name: 'Conciliación bancaria',            desc: 'Cruza los movimientos del sistema con los extractos bancarios para identificar diferencias rápidamente.' },
        { name: 'Control de centros de costo',      desc: 'Asigna gastos e ingresos a centros de costo para análisis de rentabilidad por área o proyecto.' },
        { name: 'Presupuesto y control presupuestal',desc: 'Define presupuestos anuales y controla la ejecución en tiempo real frente al presupuestado.' },
        { name: 'Integración con todos los módulos',desc: 'Las transacciones de ventas, compras, nómina e inventarios se registran contablemente de forma automática.' },
      ],
      whyTitle:    'Contabilidad integrada, no contabilidad en paralelo.',
      whySubtitle: 'SYSCOM Contabilidad no es un módulo aislado. Está integrado con toda la operación de tu empresa para que cada transacción quede registrada contablemente de forma automática.',
      whyPoints: [
        'Integración automática con facturación, nómina e inventarios',
        'Cumplimiento con normas contables colombianas (NIIF y locales)',
        'Reportes tributarios listos para la DIAN sin reprocesos',
        'Control de centros de costo y análisis de rentabilidad',
        'Parametrización según las necesidades contables de tu empresa',
      ],
      whyClosing:    'La contabilidad de tu empresa debe reflejar la realidad del negocio. SYSCOM lo garantiza.',
      benefitsTitle: 'LO QUE CAMBIA CUANDO TIENES CONTROL CONTABLE REAL',
      benefits: [
        { title: 'Información financiera confiable', desc: 'Estados financieros actualizados en tiempo real sin esperar el cierre del mes.' },
        { title: 'Cumplimiento DIAN sin estrés',     desc: 'Reportes tributarios generados automáticamente sin procesos manuales adicionales.' },
        { title: 'Sin digitación doble',             desc: 'Cada venta, compra o nómina queda en contabilidad automáticamente.' },
        { title: 'Decisiones basadas en datos',      desc: 'Información de rentabilidad por centro de costo para dirigir tu empresa con precisión.' },
        { title: 'Auditorías sin sorpresas',         desc: 'Trazabilidad completa de cada registro contable para responder a cualquier revisión.' },
      ],
      closingTitle: 'TU CONTABILIDAD DEBE SER UN ACTIVO, NO UN DOLOR DE CABEZA',
      closingDesc:  'Integra la contabilidad de tu empresa con toda la operación y toma decisiones con información financiera real, precisa y siempre disponible.',
    },

    /* ── 11. FACTURACIÓN ELECTRÓNICA ─────────────── */
    facturacionelect: {
      image: '/images/painpoints.jpg',
      bannerTitle:    'Factura electrónicamente sin errores, sin reprocesos y cumpliendo con la DIAN',
      bannerSubtitle: 'Emite facturas de venta, notas crédito, notas débito y documentos equivalentes de forma rápida y segura, integrada con tu operación y contabilidad.',
      bannerPoints: [
        'Facturas electrónicas certificadas por la DIAN',
        'Notas crédito y débito sin procesos adicionales',
        'Envío automático al adquirente por correo',
        'Integración directa con contabilidad e inventarios',
      ],
      featuresTitle: 'TODO EL CONTROL DE TU FACTURACIÓN ELECTRÓNICA, EN UN SOLO SISTEMA',
      features: [
        { name: 'Factura electrónica de venta',      desc: 'Emite facturas electrónicas con todos los campos requeridos por la DIAN y en el formato correcto.' },
        { name: 'Notas crédito y débito',            desc: 'Genera notas de ajuste relacionadas con facturas previas cumpliendo con la normativa vigente.' },
        { name: 'Documento soporte de compras',      desc: 'Emite documentos soporte para las compras a proveedores no obligados a facturar electrónicamente.' },
        { name: 'Envío automático al adquirente',    desc: 'El sistema envía la factura al correo del cliente automáticamente en el momento de la emisión.' },
        { name: 'Validación DIAN en tiempo real',    desc: 'Cada documento es validado ante la DIAN en tiempo real para garantizar su plena vigencia legal.' },
        { name: 'Gestión de clientes y tarifas',     desc: 'Administra el directorio de clientes, condiciones comerciales y listas de precios desde el sistema.' },
        { name: 'Control de cartera emitida',        desc: 'Consulta facturas emitidas, pendientes de pago y estados de cuenta de clientes en cualquier momento.' },
        { name: 'Integración contable automática',   desc: 'Cada factura queda registrada en contabilidad e inventario sin necesidad de digitación adicional.' },
      ],
      whyTitle:    'Más que un software de facturación. Tu punto de control comercial.',
      whySubtitle: 'SYSCOM Facturación Electrónica está habilitada ante la DIAN y diseñada para que el proceso de emisión sea simple, seguro y completamente integrado con tu operación.',
      whyPoints: [
        'Habilitado como proveedor tecnológico ante la DIAN',
        'Facturación integrada con inventario y contabilidad',
        'Soporte para todos los tipos de documentos electrónicos',
        'Envío automático y consulta en línea de documentos',
        'Proceso simple que no requiere conocimientos técnicos avanzados',
      ],
      whyClosing:    'Facturar electrónicamente no tiene que ser complicado. SYSCOM lo hace simple y confiable.',
      benefitsTitle: 'LO QUE CAMBIA CUANDO FACTURAS CON CONTROL REAL',
      benefits: [
        { title: 'Cumplimiento DIAN garantizado',   desc: 'Cada documento emitido cumple con la resolución y validación vigente sin riesgo de rechazos.' },
        { title: 'Proceso ágil y sin errores',      desc: 'Emite facturas en segundos con datos del cliente y producto precargados desde el sistema.' },
        { title: 'Sin papeles ni archivos manuales',desc: 'Todos tus documentos electrónicos quedan almacenados y disponibles para consulta en línea.' },
        { title: 'Cartera organizada',              desc: 'Controla qué facturas están pendientes de pago y el saldo de cada cliente en tiempo real.' },
        { title: 'Contabilidad al día',             desc: 'Cada factura queda registrada contablemente de forma automática sin pasos adicionales.' },
      ],
      closingTitle: 'FACTURAR ELECTRÓNICAMENTE ES UNA OBLIGACIÓN. HACERLO BIEN ES UNA VENTAJA.',
      closingDesc:  'Cumple con la DIAN, agiliza tu operación comercial y mantén tu cartera organizada con un sistema de facturación electrónica diseñado para empresas colombianas.',
    },

    /* ── 12. ACTIVOS FIJOS ───────────────────────── */
    activosFijos: {
      image: '/images/painpoints.jpg',
      bannerTitle:    'Controla todos los activos de tu empresa con precisión y cumplimiento contable',
      bannerSubtitle: 'Registra, clasifica y deprecia los bienes de tu empresa de forma automática y conforme a las normas contables colombianas, integrando la información con tu contabilidad.',
      bannerPoints: [
        'Registro y clasificación de activos por tipo y área',
        'Depreciación automática según normativa contable',
        'Inventario físico de activos con trazabilidad completa',
        'Integración directa con contabilidad sin digitación doble',
      ],
      featuresTitle: 'TODO EL CONTROL DE TUS ACTIVOS FIJOS, EN UN SOLO SISTEMA',
      features: [
        { name: 'Registro de activos',               desc: 'Ingresa cada activo con su descripción, valor de adquisición, fecha, área y responsable.' },
        { name: 'Clasificación y categorías',        desc: 'Organiza los activos por tipo (maquinaria, vehículos, equipos, mobiliario) para análisis segmentado.' },
        { name: 'Depreciación automática',           desc: 'Calcula la depreciación mensual por los métodos permitidos bajo la normativa contable vigente.' },
        { name: 'Vida útil y valor residual',        desc: 'Define la vida útil y el valor residual de cada activo para un cálculo exacto de la depreciación.' },
        { name: 'Inventario físico de activos',      desc: 'Realiza levantamientos físicos periódicos y cruza con el registro del sistema para detectar diferencias.' },
        { name: 'Bajas y traslados',                 desc: 'Registra la baja o traslado de activos con su respectivo registro contable automático.' },
        { name: 'Reportes por área o responsable',   desc: 'Consulta el inventario de activos asignados por área, sede o empleado responsable.' },
        { name: 'Integración contable automática',   desc: 'La depreciación y las transacciones de activos se registran en contabilidad sin pasos adicionales.' },
      ],
      whyTitle:    'Control de activos que se integra, no que se lleva aparte.',
      whySubtitle: 'SYSCOM Activos Fijos elimina las hojas de cálculo y los archivos manuales de depreciación. Todo queda integrado con la contabilidad de tu empresa de forma automática.',
      whyPoints: [
        'Depreciación automática según normas contables colombianas',
        'Integración con contabilidad sin digitación adicional',
        'Control de inventario físico con trazabilidad completa',
        'Clasificación flexible según las necesidades de tu empresa',
        'Reportes de activos para auditorías y decisiones de inversión',
      ],
      whyClosing:    'Tus activos representan valor. SYSCOM te ayuda a controlarlo y reportarlo correctamente.',
      benefitsTitle: 'LO QUE CAMBIA CUANDO CONTROLAS TUS ACTIVOS CORRECTAMENTE',
      benefits: [
        { title: 'Depreciación sin errores',          desc: 'Elimina los errores en los cálculos manuales y garantiza cifras contables precisas.' },
        { title: 'Inventario de activos actualizado', desc: 'Conoce exactamente qué tiene la empresa, dónde está y en qué estado se encuentra.' },
        { title: 'Contabilidad más limpia',           desc: 'La depreciación y movimientos de activos se reflejan automáticamente en los libros contables.' },
        { title: 'Listo para auditorías',             desc: 'Documentación completa de cada activo disponible para revisiones internas o externas.' },
        { title: 'Decisiones de inversión informadas',desc: 'Conoce el valor neto de tus activos para planificar reposiciones y nuevas adquisiciones.' },
      ],
      closingTitle: 'LO QUE NO CONTROLAS, NO PUEDES GESTIONAR NI REPORTAR',
      closingDesc:  'Deja de depreciar en Excel y de perder control de los activos de tu empresa. Integra la gestión de activos fijos con tu contabilidad de forma automática y precisa.',
    },

    /* ── 13. FACTURACIÓN E INVENTARIO ────────────── */
    facturacioneinventario: {
      image: '/images/painpoints.jpg',
      bannerTitle:    'Controla tus ventas, inventario y facturación sin errores ni reprocesos',
      bannerSubtitle: 'Emite facturas electrónicas, gestiona el inventario en tiempo real y controla tus compras y cartera desde un sistema integrado que mantiene tu operación comercial organizada.',
      bannerPoints: [
        'Facturación electrónica integrada con inventario',
        'Stock actualizado en cada venta y compra',
        'Control de cartera y cuentas por pagar',
        'Reportes de ventas e inventario en tiempo real',
      ],
      featuresTitle: 'TODO TU CICLO COMERCIAL, EN UN SOLO SISTEMA',
      features: [
        { name: 'Factura electrónica de venta DIAN', desc: 'Emite facturas electrónicas válidas ante la DIAN con actualización automática del inventario.' },
        { name: 'Notas crédito y devoluciones',      desc: 'Procesa devoluciones parciales o totales con su respectivo ajuste de inventario y nota crédito.' },
        { name: 'Control de stock en tiempo real',   desc: 'El inventario se actualiza automáticamente en cada venta, compra o devolución sin intervención manual.' },
        { name: 'Gestión de compras y proveedores',  desc: 'Crea órdenes de compra, recibe mercancía y actualiza el inventario con integración automática.' },
        { name: 'Múltiples bodegas o puntos',        desc: 'Administra el inventario de varias bodegas o puntos de venta desde un solo sistema centralizado.' },
        { name: 'Listas de precios y descuentos',    desc: 'Configura múltiples listas de precios, descuentos por volumen y condiciones especiales por cliente.' },
        { name: 'Cartera y cuentas por cobrar',      desc: 'Monitorea los saldos de clientes, vencimientos y aplica pagos directamente desde el sistema.' },
        { name: 'Reportes de ventas e inventario',   desc: 'Análisis de ventas por producto, cliente o período y reportes de rotación, stock mínimo y valorización.' },
      ],
      whyTitle:    'No es solo facturar. Es controlar todo el ciclo comercial e inventario.',
      whySubtitle: 'SYSCOM Facturación e Inventario conecta la venta con el stock y la cartera en un solo sistema, eliminando los errores que nacen de tener información en lugares separados.',
      whyPoints: [
        'Factura electrónica y actualización de inventario en un solo paso',
        'Control de compras integrado con el stock y proveedores',
        'Cartera de clientes y cuentas por pagar siempre actualizadas',
        'Manejo de múltiples bodegas y puntos de venta',
        'Cumplimiento DIAN garantizado sin procesos adicionales',
      ],
      whyClosing:    'Vender sin controlar el inventario es una pérdida anunciada. SYSCOM lo conecta todo.',
      benefitsTitle: 'LO QUE CAMBIA CUANDO CONTROLAS TODO EL CICLO',
      benefits: [
        { title: 'Sin diferencias de inventario', desc: 'Cada venta o compra actualiza el stock automáticamente, eliminando las diferencias manuales.' },
        { title: 'Facturación más ágil',          desc: 'Emite facturas electrónicas en segundos con productos y precios precargados desde el sistema.' },
        { title: 'Cartera organizada',            desc: 'Conoce exactamente qué clientes te deben, cuánto y desde cuándo para gestionar el cobro.' },
        { title: 'Cumplimiento DIAN sin esfuerzo',desc: 'Cada documento electrónico queda validado y disponible sin pasos adicionales.' },
        { title: 'Decisiones con datos reales',   desc: 'Rotación de productos, márgenes por línea y clientes más rentables disponibles en cualquier momento.' },
      ],
      closingTitle: 'VENDER SIN CONTROLAR EL INVENTARIO ES PERDER DINERO',
      closingDesc:  'Integra tu facturación electrónica con el control de inventario y cartera en un solo sistema. Empieza a operar con información real y precisa.',
    },
  },

  /* ══════════════════════════════════════════════════
     ENGLISH
  ══════════════════════════════════════════════════ */
  en: {

    shared: {
      demo:    'Request demo',
      advisor: 'Talk to an advisor',
      demoHref: DEMO_HREF,
      waHref:   WA_HREF,
    },

    /* ── 1. FREIGHT TRANSPORT ────────────────────── */
    transCarga: {
      image: '/images/transport.jpg',
      bannerTitle:    'Control your entire freight transport operation without errors or rework',
      bannerSubtitle: 'From the loading order to billing and service payment. Manage your freight transport operation with a system that integrates operational control, accounting and regulatory compliance in real time.',
      bannerPoints: [
        'Full control of trips, remittances and manifests',
        'RNDC compliance without rework',
        'Automated settlements and advances',
        'Full integration with accounting',
      ],
      featuresTitle: 'YOUR ENTIRE TRANSPORT PROCESS, IN ONE SYSTEM',
      features: [
        { name: 'Controlled rates and profitability',     desc: 'Define billing and payment rates, separating own revenues from third-party revenues with total clarity.' },
        { name: 'Automatic document control',             desc: 'Expiration alerts for driver and vehicle documents before they create operational problems.' },
        { name: 'Real-time information',                  desc: 'Access reports on remittances, dispatches, advances, billing and financial results at any time.' },
        { name: 'Complete transport operation',           desc: 'Manage from the loading order to final service delivery, with full control of every movement.' },
        { name: 'Remittances, manifests and compliance',  desc: 'Manage all operational documents with complete traceability and no rework.' },
        { name: 'Integrated legal module',                desc: 'Record and keep the history of vehicle incidents for legal control and backup.' },
        { name: 'RNDC integration (real time)',           desc: 'Direct connection to the Ministry of Transport for automatic data transmission, avoiding errors and duplicate processes.' },
        { name: 'Advances and settlements without errors',desc: 'Set advance budgets and control maximum percentages to prevent financial deviations.' },
      ],
      whyTitle:    'Not generic software. A system built for real transport.',
      whySubtitle: 'SYSCOM Freight Transport is not an adapted ERP. It is a solution created specifically for freight transport operations in Colombia.',
      whyPoints: [
        'Full integration between operations and accounting',
        'Compliance with Ministry of Transport regulations',
        'Online RNDC connection (no rework)',
        'Adapted to the real logic of transport companies',
        'Advanced parameterization according to your operation',
      ],
      whyClosing:    'While other systems force you to adapt, SYSCOM adapts to your company.',
      benefitsTitle: 'WHAT CHANGES WHEN YOU HAVE REAL CONTROL',
      benefits: [
        { title: 'Fewer errors, more efficiency', desc: 'Eliminate rework and manual errors in settlements, documents and operations.' },
        { title: 'Decisions with real data',      desc: 'Access reliable, updated information to make operational and financial decisions.' },
        { title: 'Connected operation',           desc: 'Everything flows in one system: trips, documents, accounting and financial control.' },
        { title: 'Greater profitability',         desc: 'Control advances, costs and rates to improve profitability on each trip.' },
        { title: 'Stress-free compliance',        desc: 'Meet RNDC and regulatory requirements without relying on manual or external processes.' },
      ],
      closingTitle: 'WITHOUT CONTROL, YOU ARE LOSING MONEY',
      closingDesc:  'Stop relying on manual processes, operational errors and disconnected systems. Start managing your transport company with a solution designed for your reality.',
    },

    /* ── 2. SPECIAL TRANSPORT ────────────────────── */
    transporteEspecial: {
      image: '/images/transport.jpg',
      bannerTitle:    'Manage your special transport operation with precision and full control',
      bannerSubtitle: 'Manage routes, contracts, passengers and fleet from a single system. SYSCOM Special Transport integrates operations with billing and accounting, eliminating rework.',
      bannerPoints: [
        'Route and passenger manifest control',
        'Billing per contract, route or service',
        'Driver and assigned fleet management',
        'Automatic integration with accounting',
      ],
      featuresTitle: 'YOUR ENTIRE SPECIAL TRANSPORT PROCESS, IN ONE SYSTEM',
      features: [
        { name: 'Contract and route management',    desc: 'Define contracts per company or entity, assign routes and monitor service compliance.' },
        { name: 'Passenger manifest control',       desc: 'Record passenger lists per route or service with full traceability and organized documentation.' },
        { name: 'Fleet scheduling and dispatch',    desc: 'Plan schedules, assign vehicles and drivers, and track dispatch in real time.' },
        { name: 'Billing per service or contract',  desc: 'Issue electronic invoices directly from services rendered, speeding up collection.' },
        { name: 'Driver document control',          desc: 'Expiration alerts for licenses, insurance and vehicle documents before they become a problem.' },
        { name: 'Advances and settlements',         desc: 'Set driver advances and control settlements precisely without manual calculations.' },
        { name: 'Legal and incident module',        desc: 'Incident history and notes per vehicle for legal backing and fleet control.' },
        { name: 'Real-time financial information',  desc: 'Revenue, route cost and contract profitability reports available at any time.' },
      ],
      whyTitle:    'Not a generic system. Software built for real special transport.',
      whySubtitle: 'SYSCOM Special Transport was designed for companies operating personnel, school, tourism or executive transport contracts in Colombia.',
      whyPoints: [
        'Operational logic adapted to special and personnel transport',
        'Billing integrated with operations without double entry',
        'Fleet and driver control from a single module',
        'Compliance with Ministry of Transport regulations',
        'Flexible parameterization for your type of operation',
      ],
      whyClosing:    'Your operation has its own rules. SYSCOM adapts to them, not the other way around.',
      benefitsTitle: 'WHAT CHANGES WHEN YOU HAVE REAL CONTROL',
      benefits: [
        { title: 'Fewer operational errors',          desc: 'Eliminate rework in documentation, manifests and driver settlements.' },
        { title: 'Faster billing',                    desc: 'Generate electronic invoices directly from services rendered without extra steps.' },
        { title: 'Fleet under control',               desc: 'Track vehicles, drivers and document expirations in one place.' },
        { title: 'Greater profitability per contract',desc: 'Analyze costs and revenues per contract or route to decide with real information.' },
        { title: 'Guaranteed regulatory compliance',  desc: 'Operate under Ministry of Transport requirements without external dependencies.' },
      ],
      closingTitle: 'WITHOUT CONTROL, YOU ARE LOSING PROFITABILITY',
      closingDesc:  'Stop managing contracts and routes with spreadsheets. Manage your special transport company with a system built for your operation.',
    },

    /* ── 3. URBAN BUS ────────────────────────────── */
    busUrbano: {
      image: '/images/transport.jpg',
      bannerTitle:    'Control your urban routes, fleet and operation from one system',
      bannerSubtitle: 'Manage route scheduling, dispatch control, per-trip revenues and bus fleet with an integrated system that connects operations and accounting.',
      bannerPoints: [
        'Route, shift and dispatch control',
        'Driver settlement and trip sheet management',
        'Fleet management and preventive maintenance',
        'Integration with accounting and billing',
      ],
      featuresTitle: 'YOUR ENTIRE URBAN TRANSPORT PROCESS, IN ONE SYSTEM',
      features: [
        { name: 'Route and shift management',          desc: 'Define routes, shifts and dispatch schedules with full control of daily planning.' },
        { name: 'Real-time dispatch control',          desc: 'Record departures and arrivals, control frequencies and detect operational deviations immediately.' },
        { name: 'Driver settlement',                   desc: 'Automatically calculate revenues, deductions and driver payments by trip sheet.' },
        { name: 'Trip sheet control',                  desc: 'Manage per-bus trip sheet revenues with total precision and no manual calculations.' },
        { name: 'Fleet and owner management',          desc: 'Track each vehicle, owner and affiliate information within the system.' },
        { name: 'Preventive and corrective maintenance', desc: 'Schedule maintenance, record completed work and control workshop costs per vehicle.' },
        { name: 'Automatic document control',          desc: 'Expiration alerts for SOAT, technical-mechanical inspection and driver documents.' },
        { name: 'Financial reports per route',         desc: 'Analyze revenue, costs and profitability per route, vehicle or period in real time.' },
      ],
      whyTitle:    'Built for the real operation of urban transport companies.',
      whySubtitle: 'SYSCOM Urban Bus is not an adapted generic software. It is a solution built for the operational logic of urban and passenger transport in Colombia.',
      whyPoints: [
        'Trip sheets and settlements integrated with accounting',
        'Real-time dispatch and frequency control',
        'Vehicle owner and affiliate module',
        'Compliance with Ministry of Transport regulations',
        'Parameterization for your company\'s operational model',
      ],
      whyClosing:    'Every bus company has its own logic. SYSCOM adapts to yours.',
      benefitsTitle: 'WHAT CHANGES WHEN YOU HAVE REAL CONTROL',
      benefits: [
        { title: 'Error-free settlements',        desc: 'Automate trip sheet calculations and driver payments, eliminating manual discrepancies.' },
        { title: 'More organized operation',      desc: 'Dispatches, shifts and routes managed from one system without paper or spreadsheets.' },
        { title: 'Clear financial information',   desc: 'Know each route\'s and vehicle\'s profitability with reports updated in real time.' },
        { title: 'Fleet documents up to date',    desc: 'Vehicle and driver documents always monitored to prevent legal issues.' },
        { title: 'Decisions with real data',      desc: 'Stop operating on intuition and start deciding with reliable system information.' },
      ],
      closingTitle: 'YOUR URBAN FLEET DESERVES A SYSTEM AT ITS LEVEL',
      closingDesc:  'Modernize your urban transport company management with an integrated system that connects operations, fleet and finances in real time.',
    },

    /* ── 4. VEHICLE MAINTENANCE ──────────────────── */
    mantvehicular: {
      image: '/images/transport.jpg',
      bannerTitle:    'Control your fleet maintenance without losses or unexpected breakdowns',
      bannerSubtitle: 'Schedule preventive maintenance, manage work orders, control spare parts inventory and analyze workshop costs from a single integrated system.',
      bannerPoints: [
        'Preventive and corrective maintenance scheduling',
        'Work orders with full traceability',
        'Spare parts and workshop inventory control',
        'Per-vehicle maintenance costs in real time',
      ],
      featuresTitle: 'FULL CONTROL OF YOUR WORKSHOP AND FLEET, IN ONE SYSTEM',
      features: [
        { name: 'Maintenance scheduling',       desc: 'Define maintenance plans by mileage or time and receive automatic expiration alerts.' },
        { name: 'Work orders',                  desc: 'Create, assign and track work orders with status, technician and associated costs.' },
        { name: 'Spare parts inventory control',desc: 'Manage parts and spare parts inventory with entry, exit and minimum stock control.' },
        { name: 'Per-vehicle history',          desc: 'View the complete history of maintenance, repairs and costs for each vehicle.' },
        { name: 'Workshop cost control',        desc: 'Record labor, parts and external services to know the real cost per intervention.' },
        { name: 'Fleet document alerts',        desc: 'Track expiration of SOAT, technical-mechanical inspection and regulatory documents per vehicle.' },
        { name: 'Workshop supplier management', desc: 'Control purchases from spare parts suppliers and external maintenance service providers.' },
        { name: 'Maintenance reports',          desc: 'Cost, intervention and fleet availability reports for operational decision-making.' },
      ],
      whyTitle:    'A system built for real fleet management in Colombia.',
      whySubtitle: 'SYSCOM Vehicle Maintenance is not just a control module. It is a solution that connects the workshop with your company\'s operations and finances.',
      whyPoints: [
        'Complete technical history per vehicle',
        'Integration with inventory and purchasing',
        'Real cost control per intervention',
        'Automatic alerts for scheduled maintenance',
        'Adapted to freight, special and urban transport fleets',
      ],
      whyClosing:    'A vehicle without controlled maintenance is a foreseeable loss. SYSCOM prevents it.',
      benefitsTitle: 'WHAT CHANGES WHEN YOU HAVE REAL FLEET CONTROL',
      benefits: [
        { title: 'Fewer breakdowns',               desc: 'Scheduled maintenance reduces unexpected failures and fleet downtime.' },
        { title: 'Costs under control',            desc: 'Know exactly how much it costs to maintain each vehicle and decide with real data.' },
        { title: 'Accurate spare parts inventory', desc: 'Avoid stockouts or overstocking with automated workshop stock control.' },
        { title: 'Documented fleet',               desc: 'All documents, inspections and completed work are recorded and available.' },
        { title: 'Longer fleet lifespan',          desc: 'Systematic preventive maintenance extends vehicle life and reduces costs.' },
      ],
      closingTitle: 'YOUR FLEET IS YOUR BUSINESS. PROTECT IT WITH REAL CONTROL.',
      closingDesc:  'Stop relying on spreadsheets and manual reminders. Manage your fleet maintenance with a system that works for you.',
    },

    /* ── 5. PARKING LOT ──────────────────────────── */
    parqueadero: {
      image: '/images/138148.jpg',
      bannerTitle:    'Control your parking lot with precision, speed and no revenue leakage',
      bannerSubtitle: 'Manage vehicle entry, exit, rates and billing from an integrated system that gives you full business visibility in real time.',
      bannerPoints: [
        'Vehicle entry and exit control',
        'Flexible rates by time, vehicle type or monthly pass',
        'Integrated electronic billing',
        'Revenue and occupancy reports in real time',
      ],
      featuresTitle: 'FULL CONTROL OF YOUR PARKING LOT, IN ONE SYSTEM',
      features: [
        { name: 'Entry and exit control',         desc: 'Record each vehicle\'s entry and exit with exact time, plate and parking duration.' },
        { name: 'Rates by time or type',          desc: 'Define hourly, daily or vehicle-type rates with automatic calculation at checkout.' },
        { name: 'Monthly passes and prepaid',     desc: 'Manage monthly or prepaid users, track validity and generate automatic charges.' },
        { name: 'DIAN electronic billing',        desc: 'Issue electronic invoices at the time of payment, complying with current regulations.' },
        { name: 'Cash register and payment methods', desc: 'Record cash, card or transfer payments with per-shift cash register reconciliation.' },
        { name: 'Real-time occupancy',            desc: 'Check how many vehicles are in the lot, zone availability and daily turnover.' },
        { name: 'Revenue reports',                desc: 'Revenue reports per shift, day, week or month for business financial analysis.' },
        { name: 'Multi-user per-shift control',   desc: 'Manage access by operator and control cash register reconciliation for each work shift.' },
      ],
      whyTitle:    'More than billing software. A full control system for your parking lot.',
      whySubtitle: 'SYSCOM Parking was designed for managers and operators who need real control over their operations, revenue and regulatory compliance.',
      whyPoints: [
        'Electronic billing integrated from the point of payment',
        'Per-operator and per-shift cash register control',
        'Financial reports for decision-making',
        'Rate parameterization for your business model',
        'Integration with accounting without double entry',
      ],
      whyClosing:    'Every vehicle that enters or exits is a transaction. SYSCOM does not let any go unrecorded.',
      benefitsTitle: 'WHAT CHANGES WHEN YOU HAVE REAL CONTROL',
      benefits: [
        { title: 'No revenue leakage',       desc: 'Every service is recorded and charged correctly, eliminating losses from manual errors.' },
        { title: 'Faster checkouts',         desc: 'The system automatically calculates the amount due, speeding up each vehicle\'s exit.' },
        { title: 'Billing up to date',       desc: 'Comply with DIAN by issuing electronic invoices in real time at the collection point.' },
        { title: 'Clear business information', desc: 'Know your revenues, occupancy and turnover with reports updated at any time.' },
        { title: 'Organized per-shift operation', desc: 'Each operator accounts for their shift with precise cash reconciliation and full traceability.' },
      ],
      closingTitle: 'A WELL-MANAGED PARKING LOT IS MORE PROFITABLE',
      closingDesc:  'Eliminate billing errors, losses from manual processes and lack of control. Start managing your parking lot with a system that works with you.',
    },

    /* ── 6. SERVICE STATIONS ─────────────────────── */
    estaciones: {
      image: '/images/138148.jpg',
      bannerTitle:    'Full control of your service station, from the tank to the invoice',
      bannerSubtitle: 'Manage inventories, fuel dispatch, sales and operational reports with a system that integrates all processes in real time and under current regulations.',
      bannerPoints: [
        'Inventory control by tank and product',
        'Fuel dispatch integrated with cash register',
        'Real-time DIAN electronic billing',
        'Complete operational and financial reports',
      ],
      featuresTitle: 'FULL CONTROL OF YOUR STATION, IN ONE SYSTEM',
      features: [
        { name: 'Tank and inventory control',     desc: 'Monitor fuel levels per tank, record entries and control product inventory.' },
        { name: 'Fuel dispatch',                  desc: 'Record dispatches by pump, product and value with complete traceability.' },
        { name: 'Store and lubricant sales',      desc: 'Control store, oil and complementary service sales integrated with billing.' },
        { name: 'DIAN electronic billing',        desc: 'Issue electronic invoices at the point of sale complying with current requirements.' },
        { name: 'Cash register and payment methods', desc: 'Record cash, card, voucher or credit payments with automatic per-shift reconciliation.' },
        { name: 'Purchasing and supply',          desc: 'Manage fuel and product purchase orders to keep supply under control.' },
        { name: 'Complete operational reports',   desc: 'Sales reports by shift, product, pump and period for full business analysis.' },
        { name: 'Accounting integration',         desc: 'Sales, purchases and inventories integrate automatically with accounting.' },
      ],
      whyTitle:    'Not billing software. Full control for your service station.',
      whySubtitle: 'SYSCOM Service Stations was developed for operators who need to handle multiple products, shifts and reports with precision and regulatory compliance.',
      whyPoints: [
        'Per-tank inventory updated on every dispatch',
        'Electronic billing integrated with operations',
        'Shift and cash register control without discrepancies',
        'Reports for operational and financial decisions',
        'Adapted to the real operation of stations in Colombia',
      ],
      whyClosing:    'Every liter dispatched is a transaction. SYSCOM records all of them precisely.',
      benefitsTitle: 'WHAT CHANGES WHEN YOU HAVE REAL CONTROL',
      benefits: [
        { title: 'Inventory control without losses', desc: 'Know exactly how much fuel and product you have in real time without discrepancies.' },
        { title: 'Guaranteed regulatory compliance', desc: 'Invoice electronically and operate under current regulations without manual processes.' },
        { title: 'Balanced register per shift',      desc: 'Each shift closes with an exact balance, avoiding unidentified discrepancies and losses.' },
        { title: 'Information to make better decisions', desc: 'Sales, margin and turnover reports available at any time during the day.' },
        { title: 'Connected operation',             desc: 'Dispatches, sales, purchases and accounting integrated in one system without double entry.' },
      ],
      closingTitle: 'A STATION WITHOUT CONTROL IS A STATION WITHOUT PROFITABILITY',
      closingDesc:  'Stop operating with inventory discrepancies and manual closings. Integrate your complete operation with a system built for service stations.',
    },

    /* ── 7. INDUSTRIAL PLANTS ────────────────────── */
    plantas: {
      image: '/images/138148.jpg',
      bannerTitle:    'Manage your industrial plant with full control of processes, costs and staff',
      bannerSubtitle: 'Integrate inventory, asset, payroll and accounting management in one system that optimizes production processes and improves your plant\'s operational efficiency.',
      bannerPoints: [
        'Production inventory and materials control',
        'Fixed asset and depreciation management',
        'Integrated payroll and personnel administration',
        'Operating costs and real-time accounting',
      ],
      featuresTitle: 'FULL PLANT CONTROL, IN ONE SYSTEM',
      features: [
        { name: 'Inventory and materials management', desc: 'Control entries, exits and stock of raw materials, inputs and finished products.' },
        { name: 'Fixed asset control',               desc: 'Record machinery, equipment and facilities with automatic depreciation calculation.' },
        { name: 'Production and operating costs',    desc: 'Analyze the real costs of each production process to improve efficiency and profitability.' },
        { name: 'Payroll and personnel management',  desc: 'Manage contracts, electronic payroll and personnel events integrated with accounting.' },
        { name: 'Purchase orders and suppliers',     desc: 'Manage input and materials purchases with supplier and payment terms control.' },
        { name: 'Billing and sales control',         desc: 'Record product sales and issue electronic invoices from the same system.' },
        { name: 'Accounting and financial reports',  desc: 'Financial statements, balance sheets and DIAN reports generated automatically.' },
        { name: 'Full module integration',           desc: 'Inventory, assets, payroll and accounting work together without double entry or rework.' },
      ],
      whyTitle:    'A system that understands the real operation of an industrial plant.',
      whySubtitle: 'SYSCOM Industrial Plants integrates all administrative and operational processes of your plant into a single platform, without disconnected modules or duplicated information.',
      whyPoints: [
        'Integration of inventory, assets, payroll and accounting',
        'Production costs calculated automatically',
        'Compliance with DIAN and Colombian labor regulations',
        'Supplier and purchasing management in the same system',
        'Parameterization for your company\'s production model',
      ],
      whyClosing:    'A well-controlled plant is a more profitable plant. SYSCOM gives you that control.',
      benefitsTitle: 'WHAT CHANGES WHEN YOU HAVE REAL CONTROL',
      benefits: [
        { title: 'Real production costs',          desc: 'Know exactly what it costs to produce with updated inventory and resource information.' },
        { title: 'Always accurate inventory',      desc: 'Control raw materials, inputs and finished products without discrepancies or manual errors.' },
        { title: 'Integrated payroll without rework', desc: 'Process payroll and record it in accounting without leaving the system.' },
        { title: 'Assets under control',           desc: 'Know the updated value of your machinery and equipment with automatic depreciation.' },
        { title: 'Data-driven decisions',          desc: 'Real-time financial and operational information to manage your plant with confidence.' },
      ],
      closingTitle: 'RUN YOUR PLANT WITH THE CONTROL YOUR BUSINESS DESERVES',
      closingDesc:  'Integrate your industrial plant\'s processes in one system and stop relying on scattered information, disconnected systems and manual processes.',
    },

    /* ── 8. SYSTOTAL COMMERCIAL ──────────────────── */
    sysTotalComercial: {
      image: '/images/about.jpg',
      bannerTitle:    'Control your entire commercial operation without errors or rework',
      bannerSubtitle: 'From quote to collection, SYSCOM Total Commercial integrates sales, purchasing, inventory and billing in one system that gives real control to your commercial operation.',
      bannerPoints: [
        'Full commercial cycle: quote, order, invoice',
        'Real-time inventory and stock control',
        'Accounts receivable, collections and payables management',
        'Integration with accounting without double entry',
      ],
      featuresTitle: 'YOUR ENTIRE COMMERCIAL PROCESS, IN ONE SYSTEM',
      features: [
        { name: 'Quotes and orders',                desc: 'Generate professional quotes, convert them to orders and track their status through billing.' },
        { name: 'DIAN electronic billing',          desc: 'Issue electronic invoices, credit and debit notes complying with all current requirements.' },
        { name: 'Inventory control',                desc: 'Manage product stock with entry, exit, cost and sale price control.' },
        { name: 'Purchasing management',            desc: 'Create purchase orders, manage suppliers and record merchandise entries to inventory.' },
        { name: 'Accounts receivable',              desc: 'Control customer balances, due dates and manage collections efficiently.' },
        { name: 'Accounts payable to suppliers',    desc: 'Manage supplier obligations, payment dates and cash flow.' },
        { name: 'Price lists and discounts',        desc: 'Define multiple price lists, customer or volume discounts, and commercial terms.' },
        { name: 'Sales and profitability reports',  desc: 'Sales reports by salesperson, product, customer or period for full business analysis.' },
      ],
      whyTitle:    'Not a complex ERP. The commercial system your company needs.',
      whySubtitle: 'SYSCOM Total Commercial is designed for Colombian companies that need to control their commercial operation comprehensively, without complications and in compliance with regulations.',
      whyPoints: [
        'Full commercial cycle in one system',
        'DIAN-certified electronic billing',
        'Inventory control integrated with sales and purchasing',
        'Automated receivables and supplier management',
        'Reports for commercial and financial decision-making',
      ],
      whyClosing:    'While other systems complicate things, SYSCOM simplifies your operation without losing control.',
      benefitsTitle: 'WHAT CHANGES WHEN YOU HAVE REAL CONTROL',
      benefits: [
        { title: 'Error-free sales',              desc: 'From quote to electronic invoice, the entire cycle flows without rework or errors.' },
        { title: 'Always updated inventory',      desc: 'Every sale or purchase automatically updates stock, eliminating inventory discrepancies.' },
        { title: 'Accounts receivable under control', desc: 'Always know what your customers owe you and what you owe your suppliers.' },
        { title: 'Guaranteed DIAN compliance',    desc: 'Invoice electronically and generate tax reports without extra effort.' },
        { title: 'Information to grow',           desc: 'Sales, margin and profitability reports to make decisions with real data.' },
      ],
      closingTitle: 'YOUR COMMERCIAL BUSINESS NEEDS MORE THAN A SPREADSHEET',
      closingDesc:  'Stop managing your business with disconnected systems. Integrate your entire commercial operation and start growing with real control.',
    },

    /* ── 9. PAYROLL RH ───────────────────────────── */
    nominarh: {
      image: '/images/about.jpg',
      bannerTitle:    'Process your company\'s payroll without errors and comply with DIAN',
      bannerSubtitle: 'Manage contracts, calculate settlements, generate electronic payroll and administer personnel events from an integrated system that eliminates errors and rework.',
      bannerPoints: [
        'Automatic and error-free payroll processing',
        'DIAN-certified electronic payroll',
        'Event control: sick leave, vacation, overtime',
        'Social security and payroll taxes calculated automatically',
      ],
      featuresTitle: 'FULL PAYROLL AND PERSONNEL CONTROL, IN ONE SYSTEM',
      features: [
        { name: 'Automatic payroll processing',       desc: 'Calculate salaries, deductions, benefits and net pay accurately without manual formulas.' },
        { name: 'DIAN electronic payroll',            desc: 'Generate and transmit the payroll electronic support document complying with current regulations.' },
        { name: 'Event control',                      desc: 'Record sick leave, vacation, overtime, permits and absences for correct settlement.' },
        { name: 'Social security and contributions',  desc: 'Automatically calculate EPS, pension, ARL and payroll tax contributions per employee.' },
        { name: 'Contracts and employment',           desc: 'Manage contracts, employment types, salaries and staff benefits in an organized way.' },
        { name: 'Social benefits settlement',         desc: 'Calculate severance pay, interest, service bonus and vacation accurately at any time.' },
        { name: 'Pay stubs',                          desc: 'Generate individual pay stubs for each employee with full settlement detail.' },
        { name: 'Accounting integration',             desc: 'Payroll is recorded in accounting automatically, eliminating double entry.' },
      ],
      whyTitle:    'Error-free, penalty-free, rework-free payroll. That is SYSCOM Payroll.',
      whySubtitle: 'SYSCOM Payroll RH was designed for Colombian companies that need to process payroll accurately, comply with DIAN and manage their staff in an organized way.',
      whyPoints: [
        'Automatic payroll calculation per current Colombian regulations',
        'Integrated electronic payroll without additional processes',
        'Social security and payroll taxes calculated without errors',
        'Centralized employee and event history',
        'Direct integration with accounting and payments',
      ],
      whyClosing:    'Processing payroll manually is a risk. SYSCOM makes it a reliable process.',
      benefitsTitle: 'WHAT CHANGES WHEN YOU HAVE REAL PAYROLL CONTROL',
      benefits: [
        { title: 'Accurate settlements',              desc: 'Eliminate errors in salary, benefit and deduction calculations.' },
        { title: 'Guaranteed DIAN compliance',        desc: 'Generate electronic payroll without extra effort and comply with current regulations.' },
        { title: 'Time saved',                        desc: 'What used to take days in spreadsheets is now processed in minutes.' },
        { title: 'Organized personnel records',       desc: 'Contract, event and payment history available at all times for queries and audits.' },
        { title: 'No fines or penalties',             desc: 'Timely compliance with social security, payroll taxes and tax reports.' },
      ],
      closingTitle: 'A PAYROLL ERROR CAN COST MORE THAN THE SYSTEM',
      closingDesc:  'Protect your company from errors, fines and rework. Manage your team\'s payroll with a system built for the Colombian business reality.',
    },

    /* ── 10. ACCOUNTING ──────────────────────────── */
    contabilidad: {
      image: '/images/about.jpg',
      bannerTitle:    'Manage your company\'s accounting with precision, order and regulatory compliance',
      bannerSubtitle: 'Record accounting entries, generate financial statements, comply with DIAN and make decisions with reliable, up-to-date information from an integrated system.',
      bannerPoints: [
        'Automated chart of accounts and accounting entries',
        'Financial reports: balance sheet, P&L, cash flow',
        'Tax reports: exogenous, withholding, VAT',
        'Integration with payroll, billing and inventories',
      ],
      featuresTitle: 'FULL ACCOUNTING CONTROL OF YOUR COMPANY, IN ONE SYSTEM',
      features: [
        { name: 'Configurable chart of accounts',   desc: 'Set up the chart of accounts according to Colombian regulations and your company\'s specific needs.' },
        { name: 'Accounting entries and vouchers',  desc: 'Capture income, expense, journal and adjustment vouchers with full traceability and approval control.' },
        { name: 'Automatic financial statements',   desc: 'Generate balance sheet, income statement and cash flow updated in real time.' },
        { name: 'DIAN reports',                     desc: 'Prepare exogenous data, withholding, VAT and magnetic media reports without rework.' },
        { name: 'Bank reconciliation',              desc: 'Cross system entries with bank statements to identify discrepancies quickly.' },
        { name: 'Cost center control',              desc: 'Assign expenses and revenues to cost centers for profitability analysis by area or project.' },
        { name: 'Budget and budget control',        desc: 'Define annual budgets and track execution in real time against the budgeted amount.' },
        { name: 'Integration with all modules',     desc: 'Sales, purchasing, payroll and inventory transactions are automatically recorded in accounting.' },
      ],
      whyTitle:    'Integrated accounting, not parallel accounting.',
      whySubtitle: 'SYSCOM Accounting is not an isolated module. It is integrated with all your company\'s operations so every transaction is recorded automatically.',
      whyPoints: [
        'Automatic integration with billing, payroll and inventories',
        'Compliance with Colombian accounting standards (IFRS and local)',
        'Tax reports ready for DIAN without rework',
        'Cost center control and profitability analysis',
        'Parameterization for your company\'s accounting needs',
      ],
      whyClosing:    'Your company\'s accounting must reflect business reality. SYSCOM guarantees it.',
      benefitsTitle: 'WHAT CHANGES WHEN YOU HAVE REAL ACCOUNTING CONTROL',
      benefits: [
        { title: 'Reliable financial information', desc: 'Real-time updated financial statements without waiting for month-end closing.' },
        { title: 'Stress-free DIAN compliance',   desc: 'Tax reports generated automatically without additional manual processes.' },
        { title: 'No double entry',               desc: 'Every sale, purchase or payroll entry is recorded in accounting automatically.' },
        { title: 'Data-driven decisions',         desc: 'Cost center profitability information to run your company with precision.' },
        { title: 'Audit-ready',                   desc: 'Full traceability of every accounting entry to respond to any review.' },
      ],
      closingTitle: 'YOUR ACCOUNTING SHOULD BE AN ASSET, NOT A HEADACHE',
      closingDesc:  'Integrate your company\'s accounting with all operations and make decisions with financial information that is real, accurate and always available.',
    },

    /* ── 11. ELECTRONIC BILLING ──────────────────── */
    facturacionelect: {
      image: '/images/painpoints.jpg',
      bannerTitle:    'Invoice electronically without errors, without rework and in compliance with DIAN',
      bannerSubtitle: 'Issue sales invoices, credit notes, debit notes and equivalent documents quickly and securely, integrated with your operation and accounting.',
      bannerPoints: [
        'DIAN-certified electronic invoices',
        'Credit and debit notes without extra steps',
        'Automatic delivery to recipient by email',
        'Direct integration with accounting and inventories',
      ],
      featuresTitle: 'FULL ELECTRONIC BILLING CONTROL, IN ONE SYSTEM',
      features: [
        { name: 'Sales electronic invoice',          desc: 'Issue electronic invoices with all DIAN-required fields in the correct format.' },
        { name: 'Credit and debit notes',            desc: 'Generate adjustment notes related to prior invoices complying with current regulations.' },
        { name: 'Purchase support document',         desc: 'Issue support documents for purchases from suppliers not required to invoice electronically.' },
        { name: 'Automatic delivery to recipient',   desc: 'The system automatically sends the invoice to the customer\'s email at the time of issuance.' },
        { name: 'Real-time DIAN validation',         desc: 'Each document is validated with DIAN in real time to guarantee full legal validity.' },
        { name: 'Customer and rate management',      desc: 'Manage your customer directory, commercial terms and price lists from the system.' },
        { name: 'Issued invoice control',            desc: 'View issued invoices, pending payments and customer account statements at any time.' },
        { name: 'Automatic accounting integration',  desc: 'Each invoice is recorded in accounting and inventory without additional data entry.' },
      ],
      whyTitle:    'More than billing software. Your commercial control point.',
      whySubtitle: 'SYSCOM Electronic Billing is DIAN-enabled and designed so the issuance process is simple, secure and fully integrated with your operation.',
      whyPoints: [
        'DIAN-enabled as a technology provider',
        'Billing integrated with inventory and accounting',
        'Support for all types of electronic documents',
        'Automatic delivery and online document lookup',
        'Simple process requiring no advanced technical knowledge',
      ],
      whyClosing:    'Electronic invoicing does not have to be complicated. SYSCOM makes it simple and reliable.',
      benefitsTitle: 'WHAT CHANGES WHEN YOU BILL WITH REAL CONTROL',
      benefits: [
        { title: 'Guaranteed DIAN compliance',     desc: 'Every document issued meets current resolution and validation requirements without rejection risk.' },
        { title: 'Fast, error-free process',       desc: 'Issue invoices in seconds with customer and product data preloaded from the system.' },
        { title: 'No paper or manual files',       desc: 'All your electronic documents are stored and available for online lookup.' },
        { title: 'Organized accounts receivable',  desc: 'Track which invoices are pending payment and each customer\'s balance in real time.' },
        { title: 'Accounting up to date',          desc: 'Each invoice is automatically recorded in accounting without additional steps.' },
      ],
      closingTitle: 'ELECTRONIC INVOICING IS AN OBLIGATION. DOING IT RIGHT IS AN ADVANTAGE.',
      closingDesc:  'Comply with DIAN, streamline your commercial operation and keep your accounts receivable organized with an electronic billing system designed for Colombian companies.',
    },

    /* ── 12. FIXED ASSETS ────────────────────────── */
    activosFijos: {
      image: '/images/painpoints.jpg',
      bannerTitle:    'Control all your company\'s assets with precision and accounting compliance',
      bannerSubtitle: 'Record, classify and depreciate your company\'s assets automatically and in accordance with Colombian accounting standards, integrating the information with your accounting.',
      bannerPoints: [
        'Asset recording and classification by type and area',
        'Automatic depreciation per accounting regulations',
        'Physical asset inventory with full traceability',
        'Direct accounting integration without double entry',
      ],
      featuresTitle: 'FULL FIXED ASSET CONTROL, IN ONE SYSTEM',
      features: [
        { name: 'Asset registration',              desc: 'Enter each asset with its description, acquisition value, date, area and responsible person.' },
        { name: 'Classification and categories',   desc: 'Organize assets by type (machinery, vehicles, equipment, furniture) for segmented analysis.' },
        { name: 'Automatic depreciation',          desc: 'Calculate monthly depreciation using the methods allowed under current accounting regulations.' },
        { name: 'Useful life and residual value',  desc: 'Define the useful life and residual value of each asset for an exact depreciation calculation.' },
        { name: 'Physical asset inventory',        desc: 'Conduct periodic physical counts and cross-check with the system to detect discrepancies.' },
        { name: 'Write-offs and transfers',        desc: 'Record asset write-offs or transfers with the corresponding automatic accounting entry.' },
        { name: 'Reports by area or responsible',  desc: 'View the inventory of assets assigned by area, location or responsible employee.' },
        { name: 'Automatic accounting integration',desc: 'Depreciation and asset transactions are recorded in accounting without extra steps.' },
      ],
      whyTitle:    'Asset control that integrates, not control that is kept separately.',
      whySubtitle: 'SYSCOM Fixed Assets eliminates depreciation spreadsheets and manual files. Everything integrates automatically with your company\'s accounting.',
      whyPoints: [
        'Automatic depreciation per Colombian accounting standards',
        'Accounting integration without additional data entry',
        'Physical inventory control with full traceability',
        'Flexible classification for your company\'s needs',
        'Asset reports for audits and investment decisions',
      ],
      whyClosing:    'Your assets represent value. SYSCOM helps you control and report it correctly.',
      benefitsTitle: 'WHAT CHANGES WHEN YOU CONTROL YOUR ASSETS CORRECTLY',
      benefits: [
        { title: 'Error-free depreciation',          desc: 'Eliminate manual calculation errors and ensure precise accounting figures.' },
        { title: 'Updated asset inventory',          desc: 'Know exactly what the company has, where it is and what condition it is in.' },
        { title: 'Cleaner accounting',               desc: 'Depreciation and asset movements are automatically reflected in the accounting books.' },
        { title: 'Audit-ready',                      desc: 'Complete documentation for each asset available for internal or external reviews.' },
        { title: 'Informed investment decisions',    desc: 'Know the net value of your assets to plan replacements and new acquisitions.' },
      ],
      closingTitle: 'WHAT YOU DON\'T CONTROL, YOU CAN\'T MANAGE OR REPORT',
      closingDesc:  'Stop depreciating in Excel and losing control of your company\'s assets. Integrate fixed asset management with your accounting automatically and precisely.',
    },

    /* ── 13. BILLING & INVENTORY ─────────────────── */
    facturacioneinventario: {
      image: '/images/painpoints.jpg',
      bannerTitle:    'Control your sales, inventory and billing without errors or rework',
      bannerSubtitle: 'Issue electronic invoices, manage inventory in real time and control your purchases and receivables from an integrated system that keeps your commercial operation organized.',
      bannerPoints: [
        'Electronic billing integrated with inventory',
        'Stock updated on every sale and purchase',
        'Accounts receivable and payable control',
        'Real-time sales and inventory reports',
      ],
      featuresTitle: 'YOUR ENTIRE COMMERCIAL CYCLE, IN ONE SYSTEM',
      features: [
        { name: 'DIAN sales electronic invoice',    desc: 'Issue DIAN-valid electronic invoices with automatic inventory update.' },
        { name: 'Credit notes and returns',         desc: 'Process partial or full returns with the corresponding inventory adjustment and credit note.' },
        { name: 'Real-time stock control',          desc: 'Inventory updates automatically on every sale, purchase or return without manual intervention.' },
        { name: 'Purchasing and supplier management',desc: 'Create purchase orders, receive merchandise and update inventory automatically.' },
        { name: 'Multiple warehouses or locations', desc: 'Manage inventory across multiple warehouses or sales points from one centralized system.' },
        { name: 'Price lists and discounts',        desc: 'Configure multiple price lists, volume discounts and special conditions per customer.' },
        { name: 'Accounts receivable',             desc: 'Monitor customer balances, due dates and apply payments directly from the system.' },
        { name: 'Sales and inventory reports',      desc: 'Sales analysis by product, customer or period and turnover, minimum stock and valuation reports.' },
      ],
      whyTitle:    'Not just invoicing. Full control of the commercial cycle and inventory.',
      whySubtitle: 'SYSCOM Billing & Inventory connects sales with stock and receivables in one system, eliminating errors that arise from having information in separate places.',
      whyPoints: [
        'Electronic invoice and inventory update in one step',
        'Purchasing control integrated with stock and suppliers',
        'Customer receivables and payables always up to date',
        'Multiple warehouse and sales point management',
        'Guaranteed DIAN compliance without extra processes',
      ],
      whyClosing:    'Selling without controlling inventory is a foreseeable loss. SYSCOM connects everything.',
      benefitsTitle: 'WHAT CHANGES WHEN YOU CONTROL THE FULL CYCLE',
      benefits: [
        { title: 'No inventory discrepancies', desc: 'Every sale or purchase automatically updates stock, eliminating manual discrepancies.' },
        { title: 'Faster billing',             desc: 'Issue electronic invoices in seconds with products and prices preloaded from the system.' },
        { title: 'Organized receivables',      desc: 'Know exactly which customers owe you, how much and since when to manage collection.' },
        { title: 'Effortless DIAN compliance', desc: 'Every electronic document is validated and available without extra steps.' },
        { title: 'Decisions with real data',   desc: 'Product turnover, line margins and most profitable customers available at any time.' },
      ],
      closingTitle: 'SELLING WITHOUT INVENTORY CONTROL MEANS LOSING MONEY',
      closingDesc:  'Integrate your electronic billing with inventory and receivables control in one system. Start operating with real, accurate information.',
    },
  },
}
